// ============================================================
// HiSam — carte du bureau (40 x 30 cases de 16 px)
// ============================================================
// Trois couches en chaines de caracteres (une par ligne, un caractere par case) :
//   floor   : sol, toujours dessine, jamais bloquant
//   objects : meubles et murs ; la legende dit si la case bloque (solid)
//   zones   : "." = open space, un chiffre = piece fermee. Deux personnes ne
//             se parlent que si elles sont dans la meme zone (les murs coupent la voix).
// Les noms de tuiles sont ceux de assets/tileset.json (voir tools/build_assets.py).
// Ce fichier a ete produit par un petit script de peinture de regions, mais il
// s'edite tres bien a la main : on change un caractere, on recharge.

const WORLD_MAP = {
  width: 40,
  height: 30,
  tile: 16,

  floorLegend: {
    "g": "grass",
    "=": "pavement",
    ",": "floor_carpet",
    ";": "floor_carpet_alt",
    "w": "floor_wood",
    "~": "floor_tile",
    "_": "mat",
    "1": "rug_tl", "2": "rug_tm", "3": "rug_tr",
    "4": "rug_ml", "5": "rug_mm", "6": "rug_mr",
    "7": "rug_bl", "8": "rug_bm", "9": "rug_br",
  },
  floor: [
    "gggggggggggggggggggggggggggggggggggggggg",
    "gggggggggggggggggggggggggggggggggggggggg",
    "gggggggggggggggggggggggggggggggggggggggg",
    "gggggggggggggggggggggggggggggggggggggggg",
    "gggwwwwwwwww;,;,;,;,;,;,;,;,wwwwwwwwwggg",
    "gggwwwwwwwww,;,;,;,;,;,;,;,;wwwwwwwwwggg",
    "gggwwwwwwwww;,;,;,;,;,;,;,;,wwwwwwwwwggg",
    "gggwwwwwwwww,;,;,;,;,;,;,;,;wwwwwwwwwggg",
    "gggwwwwwwwww;,;,;,;,;,;,;,;,wwwwwwwwwggg",
    "gggwwwwwwwww,;,;,;,;,;,;,;,;wwwwwwwwwggg",
    "ggg,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;ggg",
    "ggg;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,ggg",
    "ggg,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;ggg",
    "ggg;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,ggg",
    "ggg,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;ggg",
    "ggg;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,ggg",
    "ggg,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;ggg",
    "ggg;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,ggg",
    "ggg,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;ggg",
    "ggg~~~~~~~~~,;,;,;,;,;,;,;,;wwwwwwwwwggg",
    "ggg~~~~~~~~~;,;,;,;,;,;,;,;,wwwwwwwwwggg",
    "ggg~~~~~~~~~,;,;,;,;,;,;,;,;wwwwwwwwwggg",
    "ggg~~~~~~~~~;,;,;,;,;,;,;,;,ww123wwwwggg",
    "ggg~~~~~~~~~,;,;,;,;,;,;,;,;ww456wwwwggg",
    "ggg~~~~~~~~~;,;,;,____;,;,;,ww789wwwwggg",
    "ggg~~~~~~~~~,;,;,;____,;,;,;wwwwwwwwwggg",
    "ggg~~~~~~~~~;,;,;,____;,;,;,wwwwwwwwwggg",
    "gggggggggggggggggggggggggggggggggggggggg",
    "gggggggggggggggg========gggggggggggggggg",
    "gggggggggggggggg========gggggggggggggggg"
  ],

  objectsLegend: {
    "#": { tile: "wall_face", solid: true },
    "^": { tile: "wall_top", solid: true },
    "W": { tile: "wall_window", solid: true },
    "M": { tile: "wall_whiteboard", solid: true },
    "A": { tile: "wall_picture_a", solid: true },
    "a": { tile: "wall_picture_b", solid: true },
    "m": { tile: "wall_map", solid: true },
    "D": { tile: "door", solid: false },
    "G": { tile: "door_glass", solid: false },
    "d": { tile: "desk_pc", solid: true },
    "l": { tile: "desk_laptop", solid: true },
    "n": { tile: "desk_papers", solid: true },
    "o": { tile: "desk_plain", solid: true },
    "c": { tile: "chair_down", solid: false },
    "u": { tile: "chair_up", solid: false },
    "r": { tile: "chair_right", solid: false },
    "q": { tile: "chair_left", solid: false },
    "C": { tile: "chair_white_down", solid: false },
    "U": { tile: "chair_white_up", solid: false },
    "1": { tile: "table_tl", solid: true }, "2": { tile: "table_tm", solid: true }, "3": { tile: "table_tr", solid: true },
    "4": { tile: "table_bl", solid: true }, "5": { tile: "table_bm", solid: true }, "6": { tile: "table_br", solid: true },
    "(": { tile: "round_tl", solid: true }, ")": { tile: "round_tr", solid: true },
    "[": { tile: "round_bl", solid: true }, "]": { tile: "round_br", solid: true },
    "S": { tile: "sofa_tl", solid: true }, "T": { tile: "sofa_tm", solid: true }, "V": { tile: "sofa_tr", solid: true },
    "s": { tile: "sofa_bl", solid: true }, "t": { tile: "sofa_bm", solid: true }, "v": { tile: "sofa_br", solid: true },
    "Z": { tile: "armchair_top", solid: true }, "z": { tile: "armchair_bottom", solid: true },
    "i": { tile: "piano_l", solid: true }, "I": { tile: "piano_r", solid: true },
    "B": { tile: "shelf_top", solid: true }, "b": { tile: "shelf_bottom", solid: true },
    "k": { tile: "counter", solid: true },
    "K": { tile: "counter_cabinet", solid: true },
    "j": { tile: "counter_jars", solid: true },
    "J": { tile: "counter_bottles", solid: true },
    "y": { tile: "counter_sink", solid: true },
    "Y": { tile: "counter_coffee", solid: true },
    "x": { tile: "stove", solid: true },
    "F": { tile: "fridge_top", solid: true }, "f": { tile: "fridge_bottom", solid: true },
    "w": { tile: "water_cooler", solid: true },
    "p": { tile: "plant_a", solid: true },
    "P": { tile: "plant_b", solid: true },
    "h": { tile: "bush", solid: true },
    "H": { tile: "tree", solid: true },
    "%": { tile: "bin", solid: true },
    "&": { tile: "crate", solid: true },
  },
  objects: [
    "...h........H..............H........h...",
    ".H.......h....................h.......H.",
    "..^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^..",
    "..^##MWAW###^#WW##aWWm##WW#^##WmWM###^..",
    "..^...ccc..P^p......w%....P^P..CC....^..",
    "..^..r123...^....CC........^..r()....^..",
    "..^...456q..^....ll...nn...^...[]q...^..",
    "..^...uuu...^.........UU...^...UU....^..",
    "..^.........^..............^.........^..",
    "..^p........^..............^........p^..",
    "..^####D####^..............^####D####^..",
    "..^%.................................^..",
    "..^.P.......P.......P.......P......p.^..",
    "..^...cc......cc......cc......cc.....^..",
    "..^...dl......ld......dl......dd.....^..",
    "..^...nd......dn......nd......nl.....^..",
    "..^...uu......uu......uu......uu.....^..",
    "..^..................................^..",
    "..^.........P.............P..........^..",
    "..^F......&&..cc......cc....P......B.^..",
    "..^f..........dn......ld......STV..b.^..",
    "..^k..q()r....ld......dd......stv....^..",
    "..^Y..q[]r....uu......uu..........Z..^..",
    "..^j..............................z..^..",
    "..^y.................................^..",
    "..^J........................iI.......^..",
    "..^KKkxkk..p.....................w..p^..",
    "..^^^^^^^^^^^^^^^^^GG^^^^^^^^^^^^^^^^^..",
    ".H..........................h.........H.",
    ".....H....h.......................H....."
  ],

  zones: [
    "oooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooo",
    "oo....................................oo",
    "oo....................................oo",
    "oo.111111111................222222222.oo",
    "oo.111111111................222222222.oo",
    "oo.111111111................222222222.oo",
    "oo.111111111................222222222.oo",
    "oo.111111111................222222222.oo",
    "oo.111111111................222222222.oo",
    "oo.....1........................2.....oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oo....................................oo",
    "oooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooo"
  ],

  // Cases d'apparition (devant l'entree), par ordre de preference
  spawn: [[19, 25], [20, 25], [18, 25], [21, 25], [19, 24], [20, 24], [18, 24], [21, 24], [19, 26], [20, 26], [18, 26], [21, 26]],

  // Etiquettes dessinees sur le sol
  labels: [
    { x: 4.6, y: 4.8, text: "Salle Nord" },
    { x: 34.6, y: 4.8, text: "Salle Sud" },
    { x: 8, y: 19.6, text: "Cuisine" },
    { x: 32.5, y: 19.6, text: "Salon" },
  ],
};
