// ============================================================
// HiSam — carte du bureau : les locaux de l'Escalator (40 x 50 cases de 16 px)
// ============================================================
// Trois couches en chaines de caracteres (une par ligne, un caractere par case) :
//   floor   : sol, toujours dessine, jamais bloquant
//   objects : meubles et murs ; la legende dit si la case bloque (solid)
//   zones   : "." = open space, un chiffre = piece fermee, "o" = hors du plateau.
//             Deux personnes ne se parlent que si elles sont dans la meme zone
//             (les murs des salles coupent la voix).
// Les noms de tuiles sont ceux de assets/tileset.json (voir tools/build_assets.py).
// Ce fichier est produit par tools/make_map.py, mais il s'edite tres bien a la
// main : on change un caractere, on recharge.

const WORLD_MAP = {
  width: 40,
  height: 50,
  tile: 16,

  floorLegend: {
    "v": "void",
    ",": "floor_carpet",
    ";": "floor_carpet_alt",
    "w": "floor_wood",
    "m": "floor_marble",
    "~": "floor_tile",
    "1": "rug_tl", "2": "rug_tm", "3": "rug_tr",
    "4": "rug_ml", "5": "rug_mm", "6": "rug_mr",
    "7": "rug_bl", "8": "rug_bm", "9": "rug_br",
  },
  floor: [
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmm;,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmm,;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvvvvvvvvvvvvvvv,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmmmmmmmmmmmmmv;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmmmmmmmmmmmmmv,;,;,;,;,;,;,;,;,;,;,vv",
    "vvvmm123mmmmmmmmv;,;,;,;,;,;,;,;,;,;,;vv",
    "vvvmm456mmmmmmmmv,;,;~~~~~~~~~~~~~~~~~vv",
    "vvvmm789mmmmmmmmv;,;,~~~~~~~~~~~~~~~~~vv",
    "vvvmmmmmmmmmmmmmv,;,;~~~~~~~~~~~~~~~~~vv",
    "vvvmmmmmmmmmmmmmm;,;,~~~~~~~~~~~~~~~~~vv",
    "vvvmmmmmmmmmmmmmm,;,;~~~~~~~~~~~~~~~~~vv",
    "vvvmmmmmmmmmmmmmv;,;,~~~~~~~~~~~~~~~~~vv",
    "vvvvvvvvvvvvvvvvv~~~~vvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv~~~~mmmvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv~~~~mmmvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv~~~~mmmvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv~~~~vvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv~~~~mmmvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv~~~~mmmvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvv~~~~mmmvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
    "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
  ],

  objectsLegend: {
    "#": { tile: "wall_face", solid: true },
    "^": { tile: "wall_top", solid: true },
    "W": { tile: "wall_window", solid: true },
    "M": { tile: "wall_whiteboard", solid: true },
    "E": { tile: "wall_screen", solid: true },
    "A": { tile: "wall_picture_a", solid: true },
    "a": { tile: "wall_picture_b", solid: true },
    "n": { tile: "wall_map", solid: true },
    "e": { tile: "elevator", solid: true },
    "O": { tile: "elev_door_top", solid: true },
    "o": { tile: "elev_door_bottom", solid: true },
    "c": { tile: "chair_down", solid: false },
    "u": { tile: "chair_up", solid: false },
    "r": { tile: "chair_right", solid: false },
    "q": { tile: "chair_left", solid: false },
    "C": { tile: "chair_white_down", solid: false },
    "U": { tile: "chair_white_up", solid: false },
    "h": { tile: "hightable", solid: true },
    "<": { tile: "hightable_l", solid: true }, "=": { tile: "hightable_m", solid: true }, ">": { tile: "hightable_r", solid: true },
    "t": { tile: "tv_l", solid: true }, "T": { tile: "tv_m", solid: true }, "v": { tile: "tv_r", solid: true },
    "1": { tile: "bigtable_tl", solid: true }, "2": { tile: "bigtable_t", solid: true }, "3": { tile: "bigtable_tr", solid: true },
    "4": { tile: "bigtable_l", solid: true }, "5": { tile: "bigtable_c", solid: true }, "6": { tile: "bigtable_r", solid: true },
    "7": { tile: "bigtable_bl", solid: true }, "8": { tile: "bigtable_b", solid: true }, "9": { tile: "bigtable_br", solid: true },
    "!": { tile: "bigtable_t_laptop", solid: true },
    "?": { tile: "bigtable_b_laptop", solid: true },
    "(": { tile: "round_tl", solid: true }, ")": { tile: "round_tr", solid: true },
    "[": { tile: "round_bl", solid: true }, "]": { tile: "round_br", solid: true },
    "Z": { tile: "armchair_top", solid: true }, "z": { tile: "armchair_bottom", solid: true },
    "B": { tile: "shelf_top", solid: true }, "b": { tile: "shelf_bottom", solid: true },
    "k": { tile: "counter", solid: true },
    "K": { tile: "counter_cabinet", solid: true },
    "j": { tile: "counter_jars", solid: true },
    "J": { tile: "counter_bottles", solid: true },
    "y": { tile: "counter_sink", solid: true },
    "Y": { tile: "counter_coffee", solid: true },
    "@": { tile: "counter_fruits", solid: true },
    "x": { tile: "stove", solid: true },
    "F": { tile: "fridge_top", solid: true }, "f": { tile: "fridge_bottom", solid: true },
    "w": { tile: "water_cooler", solid: true },
    "p": { tile: "plant_a", solid: true },
    "P": { tile: "plant_b", solid: true },
    "{": { tile: "bin_yellow", solid: true },
    "|": { tile: "bin_brown", solid: true },
    "}": { tile: "bin_blue", solid: true },
    "Q": { tile: "cabinet_front", solid: true },
    "&": { tile: "crate", solid: true },
  },
  objects: [
    "........................................",
    "........................................",
    "..^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^.",
    "..^WW#M#####WW#^######A#######n####a##^.",
    "..^p..........P^P....................p^.",
    "..^............^......................^.",
    "..^............^......................^.",
    "..^....tTTv....^......................^.",
    "..^..r122223q..^......c.c.c.c.c.c.c...^.",
    "..^...455556...^.....12!222!222!222!3.^.",
    "..^..r455556q..^.....4555555555555556.^.",
    "..^...455556...^.....7?888?888?888?89.^.",
    "..^..r455556q..^......u.u.u.u.u.u.u...^.",
    "..^...455556...^......................^.",
    "..^..r455556q..^......................^.",
    "..^...455556...^......................^.",
    "..^..r455556q..^......................^.",
    "..^...788889...^......................^.",
    "..^.....uu.....^......c.c.c.c.c.c.c...^.",
    "..^............^.....12!222!222!222!3.^.",
    "..^............^.....4555555555555556.^.",
    "..^............^.....7?888?888?888?89.^.",
    "..^...................u.u.u.u.u.u.u...^.",
    "..^P............p....................P^.",
    "..^#####A##a###^^.....................^.",
    "..^B...........P^.....................^.",
    "..^b............^.....................^.",
    "..^.............^.....................^.",
    "..^.............^.....................^.",
    "..^.............^....................P^.",
    "..^.............^.....................^.",
    "..^.............^.........C.....C.....^.",
    "..^...Z.........^.....<=============>.^.",
    "..^...z.........^P...#################^.",
    "..^.............^....Y@jkkkJ.w..{|}...^.",
    "..^...().Z......^.....................^.",
    "..^...[].z......^.....................^.",
    "..^...................................^.",
    "..^..................FkyKxkkjkkkJkkkkk^.",
    "..^&...........p^....fQQQQQQQQQQQQQQQQ^.",
    "..^^^^^^^^^^^^^^^....^^^^^^^^^^^^^^^^^^.",
    "................^....O..^...............",
    "................^.......^...............",
    "................^....o..^...............",
    "................^....^^^^...............",
    "................^....O..^...............",
    "................^.......^...............",
    "................^....o..^...............",
    "................^^^^^^^^^...............",
    "........................................"
  ],

  zones: [
    "oooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo111111111111o......................oo",
    "ooo1111111111111......................oo",
    "ooo1111111111111......................oo",
    "oooooooooooooooo......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo2222222222222......................oo",
    "ooo22222222222222.....................oo",
    "ooo22222222222222.....................oo",
    "ooo2222222222222......................oo",
    "ooooooooooooooooo.......oooooooooooooooo",
    "ooooooooooooooooo.......oooooooooooooooo",
    "ooooooooooooooooo.......oooooooooooooooo",
    "ooooooooooooooooo.......oooooooooooooooo",
    "ooooooooooooooooo.......oooooooooooooooo",
    "ooooooooooooooooo.......oooooooooooooooo",
    "ooooooooooooooooo.......oooooooooooooooo",
    "ooooooooooooooooo.......oooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooo"
  ],

  // Cases d'apparition (dans les ascenseurs), par ordre de preference, face au couloir
  spawn: [[22, 42], [23, 42], [22, 46], [23, 46], [22, 41], [23, 41], [22, 43], [23, 43], [22, 45], [23, 45], [22, 47], [23, 47]],
  spawnDir: 1,

  // Etiquettes dessinees sur le sol
  labels: [
    { x: 5.2, y: 5.7, text: "Salle de reunion" },
    { x: 5.4, y: 28.6, text: "Petite salle" },
    { x: 35, y: 36.6, text: "Cuisine" },
    { x: 18.5, y: 47.6, text: "Ascenseurs" },
  ],
};
